name: checklist
description: A reordable checklist in flutter
version: 0.1.2
author: "Jake Bonk"
homepage: "https://github.com/jakebonk/FlutterChecklistView"

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: